### ISSUE TITLE
iOS App doesn't get EXIF info when adding photo via "Camera" (as opposed to Gallery)

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mo-mobile#37]
Differs from the closed issue (since solved) of the app never getting date/time and geoloc from the EXIF header.
(IMO a beta version can go out without solving this issue, as there's an obvious, easy work-around.)

The app now does fine when adding photos via the Gallery.
But date/time and geoloc are missing when adding photos via Camera.
iPhone Xr, iOS 15.3.1, Camera Format Most Compatible.
Another data point:
- In the App, I Create Observation, Add Photo via Camera.
- Then on the iPhone, in Photos, look at the info for the photo. See attached screenshot.
  - Saved from Mushroom Observer
  - a Date/Time
  - "No camera information"

![5635](https://user-images.githubusercontent.com/45460/161841012-1efd9db6-4eb7-40e9-bfa1-969d60afc9e9.jpeg)

**Comment by mo-nathan** [comment]
Fixed.
