### ISSUE TITLE
Need to fix new user creation/deletion for mobile app

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mo-mobile#62]
Creation: Account isn't verified and doesn't work until you get the email which takes a while.  Not clear that the mobile registration actually generates the verification email.  Logging in as a new user and asking to reverify also doesn't happen quickly.

Deletion: It acts like it works, but nothing actually happens.  Should delete user if there are no contributions and give a warning with an explanation if there are.  Should also support this behavior from the web interface.

**Comment by mo-nathan** [comment]
Email only gets sent every 5 minutes.  api2/users needs to at least send a verification email.  Would be nice if it sent the email immediately.  Might be nice to have a way to verify either automatically or using a code (e.g., NEMF2024).

**Comment by mo-nathan** [comment]
iNat is very loose regarding email verification.  It let's you immediately start adding observations.  It does send you an email asking you to verify and if you go to Account Summary you can see if you're verified or not.  Seems like a reasonable approach to me.

**Comment by nimmolo** [comment]
I would prefer the verification email system be modified to send it out immediately.

I have seen the chaos in MO production logs that has come from bot-created fake users, so i'm against letting unverified users do anything! I have no idea what iNat is thinking, but there's a reason verification is SOP on the web. 

A 5 min wait for a verification email is not ok, though. Surely we can change that.

**Comment by mo-nathan** [comment]
Current plan:

1. Ignore verification more - allow observation and image creation at minimum.  As a first pass, essentially ignore the verification bit, other than setting it if they click the verification link and allow it to be resent.  In the future maybe prevent commenting and naming if unverified?
2. Ensure that verification email gets created when mobile sign up happens.
3. Actually delete users who have no contributions that ask to be deleted.
4. Allow user self deletion from website when there are no contributions.
5. Automate purging of unverified users with no contributions after a month.
6. Implement admin functionality for disabling/anonymizing users.  Consider option to purge by data type if requested.

**Comment by mo-nathan** [comment]
@nimmolo By "chaos" do you just mean that they create a bunch of fake accounts and then don't do anything with them?  Have you seen them attempt to do anything?  I'm worried about trying to get the email verification thing working and reasonable in time for NEMF.  Ignoring verification at least in the short term seems reasonable.  Maybe they can only create observations and upload images?  Perhaps part of the reason it works for iNat is that they have a pretty aggressive manual curation process.  I think it's at least worth experimenting with easing up on the verification requirements to see what the bots do.

**Comment by mo-nathan** [comment]
One of my worries about requiring verification is that I plan to explain to folks at NEMF how it is all supposed to work the first night.  I expect at least 10% of the audience (~25 people) to scan the QR code I throw up on the screen and if they aren't members then immediately creating an account.  If this load causes issues with the email queuing and that's required to do more, then it will be a bad thing.  Maybe I'll implement it as an admin option.  Then we can test it out for a day and see what happens.  We can then turn it off until the first night of NEMF when we can turn it on.  Another interesting option is giving folks a grace period so verification isn't needed for some period of time.  Of course this doesn't help the nightmare bot situation and having some time limit just means folks get annoyed later when they aren't in the process of signing up.

**Comment by nimmolo** [comment]
Yes, my memory is that i've seen these bot-created "accounts" do actual things with the fake accounts, like tie up the server attempting impossibly taxing queries.

**Comment by JoeCohen** [comment]
When they are able to login, they also create spam comments, or even
observations.

**Comment by mo-nathan** [comment]
In thinking about this, I recalled that iNat kind of does a pseudo-captcha thing by asking the user a couple of questions related to content sharing that they need to check at least one box for.  If the user doesn't check at least one of the boxes, it pushes back.

**Comment by mo-nathan** [comment]
What if I only allow the operations that come through the mobile app.  If they are coming in through the website, they have to verify.  If this still creates messes, then we could add a verification question.

**Comment by mo-nathan** [comment]
Digging into this a bit more, I believe the only needed to allow stuff from the mobile app for non-verified users is to comment out line 273 in app/classes/api2/core/base.rb.  The only other issue I spotted is in User.cull_unverified_users which apparently gets called once a day to delete unverified users that are over a month old.  I'm thinking that modifying this to also require that the user have zero contributions would be reasonable maybe with a warning message that comes out of the cron job to ensure we review these cases.  Admins could of course do the verification for users that we think are valid or delete bad users that have managed to generate some contribution.

**Comment by nimmolo** [comment]
I feel like I'm missing something. 

Why not just alter the verification email mechanism to send immediately? That seems both like an obvious solution and necessary improvement.

**Comment by nimmolo** [comment]
Here it is in crontab:
```
*/5 * * * * /var/web/mo/bin/run rake email:send -f /var/web/mushroom-observer/Rakefile
```
How about every 15 seconds:
```
*/0.25 * * * * /var/web/mo/bin/run rake email:send -f /var/web/mushroom-observer/Rakefile
```

**Comment by nimmolo** [comment]
It also might be more desirable to move `email:send` from a cron to a job. That way it's sent ASAP at whatever priority.

**Comment by mo-nathan** [comment]
Improving the email turn around certainly helps, but still leaves a hurdle for mobile-centric newbies since it requires that they receive the email on their phone and click a link that launches a web browser.  It also depends on the MO server being functional and responsive.  While most websites rely on email verification, I'm not sure that's true of most mobile apps that are in use by 24 year olds.

**Comment by mo-nathan** [comment]
Regarding user deletion, is the existing 1 month culling mechanism enough?

**Comment by mo-nathan** [comment]
See https://github.com/MushroomObserver/mushroom-observer/pull/2430 for a draft PR for loosening the API verification requirement for API users.

**Comment by mo-nathan** [comment]
The other use case I'm worried about is 10-20 people in a bus for a foray trying to get the mobile app loaded, create an account, and dealing with the verification process with flakey wifi.  Maybe a way to address this concern is to just ensure that mobile app users can create draft observations on their phones without ever contacting the website.  Then require verification to do the upload.  That way all they need on the bus is to download the app.  They can do the upload/verification workflow when they are back in the id room where presumably there is decent wifi.

**Comment by mo-nathan** [comment]
Hmm, one added complexity with that approach is that the uniqueness of the username has to be verified by the webserver.  A thought for that is to not require user registration/login to create draft observations on the phone.  The registration process becomes part of the update process...

**Comment by nimmolo** [comment]
Every mobile app I have used requires email verification, including the "twitch"-y apps for 24-year-olds that i use.

I am not _nearly_ as wary of any of the contingencies you mentioned as I am of allowing unverified users, and that's coming from all the painful, distracting work Joe, Jason and I (and iirc, you!) did a year or so back clamping down on all the shenanigans on production. That stuff was not fun, and it came from MO's years of going against common sense in terms of web security.

I think this is simply the wrong approach. Let's quicken the emails to every 15 seconds, and see if that doesn't solve  everything.

**Comment by mo-nathan** [comment]
So my 18 year old said it would strike them as weird and mildly annoying that a "fun" app like MO would require email verification.  They expect that from banks and other financial apps, but not for something that doesn't involve money.  Maybe for NEMF we just try to make the email go faster and I keep an ear out for more feedback like that.

**Comment by mo-nathan** [comment]
BTW, from what I read on the interwebs cron can't be used for time intervals under 1 minute.  Solid queue seems like a better solution, but will require more code change.

**Comment by mo-nathan** [comment]
Realized we can probably just make a first attempt to send the verification email when it gets initially queued.  See https://github.com/MushroomObserver/mushroom-observer/pull/2433.  If it fails then it goes into the queue per usual to be handled by cron.

**Comment by mo-nathan** [comment]
Closing this out.  Given that it now sends the email immediately and unused accounts are deleted after a month, I think we're fine.
